We now determine the signedness of wchar_t at configure time.
You must re-run configure after checkout.


git-svn-id: https://source.seas.harvard.edu/svn/cyclone/trunk/cyclone@2571 581db07f-6e62-4d40-9733-d432c4eebb07

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2622,7 +2622,7 @@ if [ "$ac_cv_sizeof_int" != "$ac_cv_sizeof_void_p" ]; then
   exit
 fi
 
-# The compiler needs to know the size of wchar_t
+# The compiler needs to know the size of wchar_t...
 echo "$as_me:2626: checking for wchar_t" >&5
 echo $ECHO_N "checking for wchar_t... $ECHO_C" >&6
 if test "${ac_cv_type_wchar_t+set}" = set; then
@@ -2860,8 +2860,54 @@ cat >>confdefs.h <<EOF
 #define SIZEOF_WCHAR_T $ac_cv_sizeof_wchar_t
 EOF
 
+# ... and whether it is unsigned
+echo "$as_me:2864: checking whether wchar_t is unsigned" >&5
+echo $ECHO_N "checking whether wchar_t is unsigned... $ECHO_C" >&6
+if test "${ac_cv_c_wchar_t_unsigned+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line 2870 "configure"
+#include "confdefs.h"
+$ac_includes_default
+int
+main ()
+{
+int _array_ [1 - 2 * !(((wchar_t) -1) < 0)]
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:2882: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:2885: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:2888: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:2891: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_wchar_t_unsigned=no
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_c_wchar_t_unsigned=yes
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:2901: result: $ac_cv_c_wchar_t_unsigned" >&5
+echo "${ECHO_T}$ac_cv_c_wchar_t_unsigned" >&6
+if test $ac_cv_c_wchar_t_unsigned = yes; then
+  WCHAR_T_UNSIGNED=1
+else
+  WCHAR_T_UNSIGNED=0
+fi
+
 # The rest...
-echo "$as_me:2864: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "$as_me:2910: checking whether ${MAKE-make} sets \${MAKE}" >&5
 echo $ECHO_N "checking whether ${MAKE-make} sets \${MAKE}... $ECHO_C" >&6
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y,./+-,__p_,'`
 if eval "test \"\${ac_cv_prog_make_${ac_make}_set+set}\" = set"; then
@@ -2881,11 +2927,11 @@ fi
 rm -f conftest.make
 fi
 if eval "test \"`echo '$ac_cv_prog_make_'${ac_make}_set`\" = yes"; then
-  echo "$as_me:2884: result: yes" >&5
+  echo "$as_me:2930: result: yes" >&5
 echo "${ECHO_T}yes" >&6
   SET_MAKE=
 else
-  echo "$as_me:2888: result: no" >&5
+  echo "$as_me:2934: result: no" >&5
 echo "${ECHO_T}no" >&6
   SET_MAKE="MAKE=${MAKE-make}"
 fi
@@ -2893,7 +2939,7 @@ fi
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
-echo "$as_me:2896: checking for $ac_word" >&5
+echo "$as_me:2942: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_RANLIB+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -2908,7 +2954,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_RANLIB="${ac_tool_prefix}ranlib"
-echo "$as_me:2911: found $ac_dir/$ac_word" >&5
+echo "$as_me:2957: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -2916,10 +2962,10 @@ fi
 fi
 RANLIB=$ac_cv_prog_RANLIB
 if test -n "$RANLIB"; then
-  echo "$as_me:2919: result: $RANLIB" >&5
+  echo "$as_me:2965: result: $RANLIB" >&5
 echo "${ECHO_T}$RANLIB" >&6
 else
-  echo "$as_me:2922: result: no" >&5
+  echo "$as_me:2968: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -2928,7 +2974,7 @@ if test -z "$ac_cv_prog_RANLIB"; then
   ac_ct_RANLIB=$RANLIB
   # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
-echo "$as_me:2931: checking for $ac_word" >&5
+echo "$as_me:2977: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_ac_ct_RANLIB+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -2943,7 +2989,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_ac_ct_RANLIB="ranlib"
-echo "$as_me:2946: found $ac_dir/$ac_word" >&5
+echo "$as_me:2992: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -2952,10 +2998,10 @@ fi
 fi
 ac_ct_RANLIB=$ac_cv_prog_ac_ct_RANLIB
 if test -n "$ac_ct_RANLIB"; then
-  echo "$as_me:2955: result: $ac_ct_RANLIB" >&5
+  echo "$as_me:3001: result: $ac_ct_RANLIB" >&5
 echo "${ECHO_T}$ac_ct_RANLIB" >&6
 else
-  echo "$as_me:2958: result: no" >&5
+  echo "$as_me:3004: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3075,7 +3121,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3078: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3124: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3242,7 +3288,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3245: error: ambiguous option: $1
+    { { echo "$as_me:3291: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3261,7 +3307,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3264: error: unrecognized option: $1
+  -*) { { echo "$as_me:3310: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3297,7 +3343,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile.inc" ) CONFIG_FILES="$CONFIG_FILES Makefile.inc" ;;
-  *) { { echo "$as_me:3300: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3346: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3391,6 +3437,7 @@ s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
 s,@CPP@,$CPP,;t t
 s,@ac_cv_sizeof_wchar_t@,$ac_cv_sizeof_wchar_t,;t t
+s,@WCHAR_T_UNSIGNED@,$WCHAR_T_UNSIGNED,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
 s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
@@ -3503,7 +3550,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3506: creating $ac_file" >&5
+    { echo "$as_me:3553: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3521,7 +3568,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3524: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3571: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3534,7 +3581,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3537: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3584: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
