I added support for storing architectures as patches.  As an example, I included a port to Sun.
(Everyone needs to redo ./configure ...)

The build procedure is the same as before: make everything under
your own architecture for as long as you like, but NEVER
DO A MAKE UPDATE DIRECTLY.  Instead, once you are ready to commit,
do a make update_all_archs; I have modified its behavior to update
all supported architectures, including your own.

The magic is in the update_all_archs target.  This
routine cycles through every architecture, and extracts it from
its patch, if a patch for it exists.  Then, for every architecture,
it does a make update, thus propogating changes for all architectures.
Finally, for those architectures that were originally patches,
it regenerates the patch from the now-updated reference
architecture, which is i686-unknown-linux (the reference architecture
name is stored in the variable PATCH_ARCH, defined in Makefile.inc).
Finally, it removes the directories for the architectures that
have patches, just leaving the patch behind.

In terms of savings, the .c files for Sun were roughly 4 MB,
while the patch is only 15K.

Notes:

In truth, doing a make update is fine if you are not developing
on Linux.  If you are on Linux, doing a make update will change
the files upon which the patches for other architectures
depend, so this is a no no.

If folks start to feel like supporting lots of architectures in
this way is a hassle, we can easily avoid it by truncating the
ALL_ARCHS variable in Makefile.inc to be just linux and cygwin.
Then we can build patches and so forth for other archs only
at release time.  However, this means we have to ultimately
build on some other architecture each time we do a release to
regenerate the .c files.


git-svn-id: https://source.seas.harvard.edu/svn/cyclone/trunk/cyclone@1393 581db07f-6e62-4d40-9733-d432c4eebb07

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,10 +2,40 @@
 # Architecture-specific configuration.
 # 
 # usage: configure
+#
+# TODO:
+#   better job of finding egrep
+#   locate bash on the system (on the Cornell suns it's /usr/local/gnu/bin/bash
+#
 
 # get the root directory of the source tree
 CYCDIR=`pwd`
 
+###########################################################################
+# functions to find appropriate helper programs
+#
+
+# egrep_path <arch>
+#   given the architecture, outputs a suitable version of egrep
+
+function egrep_path {
+  TARGET=`echo $1 | awk -F'-' '{ print $1 }'`
+  TYPE=`echo $1 | awk -F'-' '{ print $2 }'`
+  OS=`echo $1 | awk -F'-' '{ print $3 }'`
+  EGREP="egrep"
+  if [ "$TYPE" = "sun" ]; then
+    f="/usr/xpg4/bin/egrep"
+    if [ -f "$f" ]; then
+      EGREP=$f
+    else
+      echo "Warning: could not find $f"
+      echo "  file include/arch/$1.h may be incorrect/incomplete"
+    fi
+  fi
+  echo $EGREP
+}
+
+###########################################################################
 #  incdir="$CYCDIR/include"
 #  libdir="$CYCDIR/bin/cyc-lib"
 #  bindir=
@@ -66,7 +96,7 @@ function cleanup {
 }
 
 # see if we have #defines for this architecture
-if [ ! -f "arch/${ARCH}" ] || [ ! -f "arch/${ARCH}.undef" ]; then
+if [ ! -f "arch/${ARCH}" ]; then
   echo "This architecture is currently unsupported.  Set it up (y/n)?"
   read resp
   if [ "$resp" = "y" ]; then
@@ -81,6 +111,8 @@ if [ ! -f "arch/${ARCH}" ] || [ ! -f "arch/${ARCH}.undef" ]; then
       cleanup
     fi
     echo "Creating architecture-specific include file"
+    EGREP=`egrep_path ${ARCH}`
+    export EGREP
     ./arch_include > ${CYCDIR}/lib/arch/${ARCH}.h
     cp ${CYCDIR}/lib/arch/${ARCH}.h ${CYCDIR}/include/arch/${ARCH}.h
     if [ $? != 0 ]; then
@@ -91,6 +123,30 @@ if [ ! -f "arch/${ARCH}" ] || [ ! -f "arch/${ARCH}.undef" ]; then
     if [ -d "${CYCDIR}/bin/genfiles/${ARCH}" ]; then
       echo "Warning: genfiles directory for ${ARCH} exists"
     else
+      # this code is replicated below; change both places
+      mkdir ${CYCDIR}/bin/genfiles/${ARCH}
+      case "${ARCH}" in
+      *cygwin*)
+        DEF_ARCH=i686-unknown-cygwin1.3.2;;
+      *)
+        DEF_ARCH=i686-unknown-linux
+      esac
+      echo "Using the genfiles from ${DEF_ARCH}" 
+      cp -r ${CYCDIR}/bin/genfiles/${DEF_ARCH}/* ${CYCDIR}/bin/genfiles/${ARCH}
+      CVS_files=`find ${CYCDIR}/bin/genfiles/${ARCH} -name CVS`
+      \rm -rf $CVS_files
+    fi
+  else
+    echo "aborting."
+    exit 1
+  fi
+else
+  # make sure all of the needed configuration files are here
+  if [ -f "arch/${ARCH}.undef" -a -f "../lib/arch/${ARCH}.h" -a -f "../include/arch/${ARCH}.h" ]; then
+    echo "Supported architecture ${ARCH}"
+    if [ ! -d "${CYCDIR}/bin/genfiles/${ARCH}" ]; then
+      echo "Warning: genfiles directory for ${ARCH} not present"
+      # XXX replicates the code above
       mkdir ${CYCDIR}/bin/genfiles/${ARCH}
       case "${ARCH}" in
       *cygwin*)
@@ -103,11 +159,9 @@ if [ ! -f "arch/${ARCH}" ] || [ ! -f "arch/${ARCH}.undef" ]; then
       find ${CYCDIR}/bin/genfiles/${ARCH} -name CVS -exec rm -rf {} \;
     fi
   else
-    echo "aborting."
-    exit 1
+    echo "Error---missing configuration files for ${ARCH}; rerun configure"
+    cleanup
   fi
-else
-  echo "Supported architecture ${ARCH}"
 fi
 
 # set up the installation paths
