Cleanup.  Extraneous files removed.  Makedist no longer uses .version file; there's a VERSION variable in Makefile.inc.in. Cycbison no longer prints blacklisted blocks on Mac.
git-svn-id: https://source.seas.harvard.edu/svn/cyclone/trunk/cyclone@2422 581db07f-6e62-4d40-9733-d432c4eebb07

diff --git a/makedist b/makedist
--- a/makedist
+++ b/makedist
@@ -1,55 +1,34 @@
-#!/bin/bash
+#!/bin/sh
 # Generates a .tar.gz file containing all of the files to distribute.
 # It gathers all of the files in the cyclone source tree, minus those
 # appearing the file .excludelist.  This file should contain a bunch
 # of regular expressions of filenames to exclude.
 #
 # TODO:
-# 1) automatically generate a version # to include in the compiler
-# 2) tag the CVS repository with this version #
-# 3) tar the files into the directory $PWD-$version
+# 1) tar the files into the directory $PWD-$version
 #
 # usage: makedist [version_num]
 
 TMP=/tmp/makedist$$
 
-if [ $# != 1 ]; then
-  if [ $# != 0 ]; then
-    echo "usage: $0 [version_num]"
-    exit 1
-  else
-    if [ -f ".version" ]; then
-      version=`cat .version`
-      echo "Making distribution for version $version; OK? (y/n)"
-      read resp
-      if [ "$resp" != "y" ]; then
-        echo "aborting---please specify a version #"
-	exit 1
-      fi
-    else
-      echo "aborting---no .version file and no version specified"
-      exit 1
-    fi
-  fi
+if [ $# != 0 ]; then
+  echo "usage: $0 [version_num]"
+  exit 1
 else
-  version=$1
-  if [ -f ".version" ]; then
-    fileversion=`cat .version`
-    echo "override .version file's version $fileversion with arg $version? (y/n)"
-    read resp
-    if [ "$resp" != "y" ]; then
-      echo "aborting---omit version argument to use .version file"
-      exit 1
-    fi
+  version=`make version`
+  echo "Making distribution for version $version; OK? (y/n)"
+  read resp
+  if [ "$resp" != "y" ]; then
+    echo "aborting---please specify a version #"
+    exit 1
   fi
-  echo $version > .version
 fi
 
 # grepexpr 
 #   given the file .excludelist which has elements x y z ..., it echos
 #   a string of the form x|y|z to be used as the expression to egrep.
 #
-function grepexpr {
+grepexpr () {
   first=0
   if [ -f ".excludelist" ]; then
     for file in `cat .excludelist`; do
