Some changes to get things to properly build on SunOS.  I changed realconfigure to make sure we are using GNU diff---if not, the patches might not work properly.
git-svn-id: https://source.seas.harvard.edu/svn/cyclone/trunk/cyclone@1833 581db07f-6e62-4d40-9733-d432c4eebb07

diff --git a/config/realconfigure b/config/realconfigure
--- a/config/realconfigure
+++ b/config/realconfigure
@@ -27,6 +27,30 @@ fi
 ###########################################################################
 # functions to find appropriate helper programs
 #
+TMPFILE=/tmp/cyconfig$$
+
+# diff_path <arch>
+#   given the architecture, outputs a suitable version of diff
+
+function diff_path {
+  DIFF="diff"
+  # make sure it's GNU diff
+  $DIFF --version > $TMPFILE 2>&1
+  grep GNU $TMPFILE
+  if [ $? != 0 ]; then
+    if [ "$TYPE" = "sun" ]; then
+      f="/usr/local/gnu/diffutils-2.6/bin/diff"
+      if [ -f "$f" ]; then
+        DIFF=$f
+      else
+        echo "Warning: could not find $f"
+        echo "  file include/arch/$1.h may be incorrect/incomplete"
+      fi
+    fi
+  fi
+  rm -f $TMPFILE
+  echo $DIFF
+}
 
 # egrep_path <arch>
 #   given the architecture, outputs a suitable version of egrep
@@ -241,6 +265,7 @@ ALL_ARCHS=`cd arch; \ls -1 | grep -v undef | grep -v CVS | awk '{printf("%s ",$1
 
 # get default load flags
 LD_FLAGS=`get_ldflags`
+DIFF=`diff_path`
 
 # write the config Makefile
 cd ..
@@ -259,6 +284,7 @@ ALL_ARCHS=${ALL_ARCHS}
 CC=${CC}
 LDFLAGS=${LD_FLAGS}
 SHELL=${CONFIGSHELL}
+DIFF=${DIFF}
 
 EOF
 cat Makefile.inc.in) > Makefile.inc
