Modified the shootout tests to 1) minimize cosmetic diffs 2) perform the timing inside the programs rather than with /usr/bin/time
Added additional port of strcat; wordfreq is almost there.


git-svn-id: https://source.seas.harvard.edu/svn/cyclone/trunk/cyclone@1641 581db07f-6e62-4d40-9733-d432c4eebb07

diff --git a/tests/shootout/runtests b/tests/shootout/runtests
--- a/tests/shootout/runtests
+++ b/tests/shootout/runtests
@@ -3,57 +3,72 @@
 # to stdout, one line per executable, with the elapsed times for each
 # iteration on the line.
 #
-# usage: runtests [n]
+# usage: runtests [n [testname1] [testname2] ...]
 #   where n is the number of iterations per test.
+
+TEST=./test.sh
+
+BENCHMARKS="ackermann ary3 except fibo hash hash2 heapsort lists matrix nestedloop random reversefile sieve spellcheck strcat sumcol wc"
 
 if [ $# -lt 1 ]; then
 N=1
 else
 N=$1
+shift
+if [ $# != 0 ]; then
+BENCHMARKS=$*
 fi
-
-TEST=./test.sh
-
-#BENCHMARKS="ackermann ary3 except fibo hash hash2 heapsort hello matrix nestedloop random reversefile sieve sumcol wc lists spellcheck"
-BENCHMARKS="ackermann ary3 fibo hash hash2 heapsort hello matrix nestedloop random reversefile sieve sumcol wc"
+fi
 
 function getargs {
   case "$1" in
     ackermann) echo 8;;
     ary3) echo 7000;;
+    echo) echo 100000;;
+    except) echo 200000;;
     fibo) echo 32;;
     hash) echo 80000;;
     hash2) echo 150;;
     heapsort) echo 80000;;
     hello) echo 200;;
+    lists) echo 16;;
     matrix) echo 300;;
     nestedloop) echo 16;;
     random) echo 900000;;
+    regexpmatch) echo 9000;;
     reversefile) echo 20;;
     sieve) echo 900;;
+    spellcheck) echo 10;;
+    strcat) echo 40000;;
     sumcol) echo 1000;;
     wc) echo 2000;;
+    wordfreq) echo 20;;
     *) echo "failure"; exit 1;;
+#      ackermann) echo 10;;
+#      ary3) echo 50000;;
+#      fibo) echo 38;;
+#      hash) echo 120000;;
+#      hash2) echo 100;;
+#      heapsort) echo 900000;;
+#      hello) echo 200;;
+#      matrix) echo 280;;
+#      nestedloop) echo 16;;
+#      random) echo 900000;;
+#      reversefile) echo 20;;
+#      sieve) echo 900;;
+#      sumcol) echo 1000;;
+#      wc) echo 2000;;
+#      *) echo "failure"; exit 1;;
   esac
 }
 
 function getinputfile {
   case "$1" in
-    ackermann) echo;;
-    ary3) echo ;;
-    fibo) echo ;;
-    hash) echo ;;
-    hash2) echo ;;
-    heapsort) echo ;;
-    hello) echo ;;
-    matrix) echo ;;
-    nestedloop) echo ;;
-    random) echo ;;
     reversefile) echo reversefile-Input;;
-    sieve) echo;;
+    spellcheck) echo spell-Input;;
     sumcol) echo sumcol-Input;;
     wc) echo wc-Input;;
-    *) echo "failure"; exit 1;;
+    *) echo ;;
   esac
 }  
 
@@ -66,5 +81,5 @@ do
   $TEST $N "./${file} $ARGS" $INPUTFILE
   $TEST $N "./gcc-${file} $ARGS" $INPUTFILE
   $TEST $N "./nocheck-${file} $ARGS" $INPUTFILE
-  $TEST $N "./nobounds-${file} $ARGS" $INPUTFILE
+#  $TEST $N "./nobounds-${file} $ARGS" $INPUTFILE
 done
